### ISSUE TITLE
not worls

### ISSUE THREAD

**Issue by mixserrm999** [mrepol742/Facebook-ChatBot-using-OpenAI#2]
WARN login Cannot get sequence ID with new RegExp. Fallback to old RegExp (without seqID)...
info login Got this account's message region: PRN
info login [Unused] Polling endpoint: https://edge-chat.facebook.com/mqtt/pull?region=prn",subscribedTopics:[],capabilities:10,clientCapabilities:3,chatVisibility:true,hostNameOverride:""},
info login Done logging in.
ERR! getSeqId {
ERR! getSeqId   error: 'Not logged in',
ERR! getSeqId   res: {
ERR! getSeqId     __ar: 1,
ERR! getSeqId     error: 1357004,
ERR! getSeqId     errorSummary: 'Sorry, something went wrong',
ERR! getSeqId     errorDescription: 'Please try closing and re-opening your browser window.',
ERR! getSeqId     payload: null,
ERR! getSeqId     hsrp: { hblp: [Object] },
ERR! getSeqId     lid: '7245520661439745814'
ERR! getSeqId   }
ERR! getSeqId }
ERR! [object Object]

**Comment by mrepol742** [comment]
It might happened if you logout your facebook account in browser or facebook log it out.

Re-login and get the new appstate and use it.

**Comment by mixserrm999** [comment]
its tell data
info login Got this account's message region: PRN
info login Done logging in.
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Array
    at Object.writeFileSync (node:fs:2239:5)
    at C:\Users\Administrator\Desktop\Facebook-ChatBot-using-OpenAI-master\index.js:72:16
    at C:\Users\Administrator\Desktop\Facebook-ChatBot-using-OpenAI-master\node_modules\fca-unofficial\src\listenMqtt.js:205:26
    at MqttClient.<anonymous> (C:\Users\Administrator\Desktop\Facebook-ChatBot-using-OpenAI-master\node_modules\fca-unofficial\src\listenMqtt.js:205:60)
    at MqttClient.emit (node:events:513:28)
    at MqttClient._handlePublish (C:\Users\Administrator\Desktop\Facebook-ChatBot-using-OpenAI-master\node_modules\mqtt\lib\client.js:1162:12)
    at MqttClient._handlePacket (C:\Users\Administrator\Desktop\Facebook-ChatBot-using-OpenAI-master\node_modules\mqtt\lib\client.js:351:12)
    at work (C:\Users\Administrator\Desktop\Facebook-ChatBot-using-OpenAI-master\node_modules\mqtt\lib\client.js:283:12)    at writable._write (C:\Users\Administrator\Desktop\Facebook-ChatBot-using-OpenAI-master\node_modules\mqtt\lib\client.js:294:5)
    at doWrite (C:\Users\Administrator\Desktop\Facebook-ChatBot-using-OpenAI-master\node_modules\mqtt\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (C:\Users\Administrator\Desktop\Facebook-ChatBot-using-OpenAI-master\node_modules\mqtt\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at Writable.write (C:\Users\Administrator\Desktop\Facebook-ChatBot-using-OpenAI-master\node_modules\mqtt\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at Duplexify.ondata (C:\Users\Administrator\Desktop\Facebook-ChatBot-using-OpenAI-master\node_modules\duplexify\node_modules\readable-stream\lib\_stream_readable.js:619:20)
    at Duplexify.emit (node:events:513:28)
    at addChunk (C:\Users\Administrator\Desktop\Facebook-ChatBot-using-OpenAI-master\node_modules\duplexify\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (C:\Users\Administrator\Desktop\Facebook-ChatBot-using-OpenAI-master\node_modules\duplexify\node_modules\readable-stream\lib\_stream_readable.js:278:11) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by mrepol742** [comment]
Hello @mixserrm999 

```
git pull
```
It should work now

![image](https://github.com/mrepol742/Facebook-ChatBot-using-OpenAI/assets/62317165/2eeca650-79ad-43a8-9399-9cd17b4a78a4)

**Comment by mixserrm999** [comment]
![image](https://github.com/mrepol742/Facebook-ChatBot-using-OpenAI/assets/61624005/cde2981f-d462-405d-83f0-3ad1be04bfa1)

**Comment by mixserrm999** [comment]
like it

**Comment by mrepol742** [comment]
Thank you @mixserrm999 

If you want to use thr project orion AI api you can call this endpoint

https://project-orion.mrepol742.repl.co/chat using GET method in 0.0.0.0:8000 or localhost.

The format are
chat?first_message_goes_here%jk__lio&old_message_goes_here

Example are here using ajax.
https://github.com/mrepol742/mrepol742.github.io/blob/master/js/chat.js

**Comment by mrepol742** [comment]
> ![image](https://user-images.githubusercontent.com/61624005/246592314-cde2981f-d462-405d-83f0-3ad1be04bfa1.png)

if this error persist git pull from the repository to reflect my changes.

```
git pull
```

**Comment by mixserrm999** [comment]
thx you is work
